apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: newcluster
  region: ap-south-1

nodeGroups:
  - name: nodegroup1
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      publicKeyName : reddy
  - name: nodegroup2
    instanceType: t2.small
    desiredCapacity: 1
    ssh:
      publicKeyName : reddy
  - name: ng-mixed
    minSize: 2
    maxSize: 5
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t3.small","t3.medium"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      SpotInstancePools: 2
    ssh:
      publicKeyName: reddy
  
      
